'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {createClient} from '@/lib/supabase/client'
export default function Profile(){
 const s=createClient();const [user,setUser]=useState<any>(null);const [name,setName]=useState('');const [phone,setPhone]=useState('');const [email,setEmail]=useState('');const [address,setAddress]=useState('');const [city,setCity]=useState('');const [province,setProvince]=useState('');const [postal,setPostal]=useState('');const [msg,setMsg]=useState('');const [busy,setBusy]=useState(false)
 useEffect(()=>{(async()=>{const {data}=await s.auth.getUser();if(!data.user)return;setUser(data.user);setEmail(data.user.email||'');const {data:c,error}=await s.from('btp_customers').select('full_name,phone,email,address,city,province,postal_code').eq('auth_user_id',data.user.id).maybeSingle();if(error)setMsg(error.message);if(c){setName(c.full_name||'');setPhone(c.phone||'');setEmail(c.email||data.user.email||'');setAddress(c.address||'');setCity(c.city||'');setProvince(c.province||'');setPostal(c.postal_code||'')}})()},[])
 async function save(e:React.FormEvent){e.preventDefault();if(!user)return;setBusy(true);setMsg('');const payload={auth_user_id:user.id,full_name:name.trim(),phone:phone.trim(),email:email.trim()||null,address:address.trim()||null,city:city.trim()||null,province:province.trim()||null,postal_code:postal.trim()||null,updated_at:new Date().toISOString()};const {error}=await s.from('btp_customers').upsert(payload,{onConflict:'auth_user_id'});setMsg(error?'Gagal menyimpan: '+error.message:'Profil dan alamat berhasil disimpan.');setBusy(false)}
 if(!user)return <main className="container" style={{padding:'50px 0',maxWidth:680}}><h1>Profil</h1><p className="muted">Silakan masuk terlebih dahulu.</p><Link className="btn primary" href="/auth/login">Masuk</Link></main>
 return <main className="container" style={{padding:'40px 0 80px',maxWidth:760}}><p className="muted">AKUN · PROFIL</p><h1>Profil & Alamat</h1><p className="muted">Simpan data sekali agar checkout berikutnya lebih cepat.</p><form onSubmit={save} style={{display:'grid',gap:14}}><section className="card" style={{padding:22,display:'grid',gap:12}}><h3 style={{margin:0}}>Data pelanggan</h3><input required placeholder="Nama lengkap" value={name} onChange={e=>setName(e.target.value)} style={{padding:13,borderRadius:10}}/><input required placeholder="Nomor WhatsApp" value={phone} onChange={e=>setPhone(e.target.value)} style={{padding:13,borderRadius:10}}/><input type="email" placeholder="Email" value={email} disabled style={{padding:13,borderRadius:10}}/></section><section className="card" style={{padding:22,display:'grid',gap:12}}><h3 style={{margin:0}}>Alamat pengiriman utama</h3><textarea required placeholder="Alamat lengkap: jalan, nomor rumah, RT/RW, patokan" value={address} onChange={e=>setAddress(e.target.value)} rows={4} style={{padding:13,borderRadius:10}}/><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(200px,1fr))',gap:10}}><input placeholder="Kota/Kabupaten" value={city} onChange={e=>setCity(e.target.value)} style={{padding:13,borderRadius:10}}/><input placeholder="Provinsi" value={province} onChange={e=>setProvince(e.target.value)} style={{padding:13,borderRadius:10}}/><input placeholder="Kode pos" value={postal} onChange={e=>setPostal(e.target.value)} style={{padding:13,borderRadius:10}}/></div></section><button className="btn primary" disabled={busy}>{busy?'Menyimpan…':'Simpan Profil & Alamat'}</button>{msg&&<p>{msg}</p>}</form></main>
}
