'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { createClient } from '@/lib/supabase/client'\nimport AdminNav from '../AdminNav'

const money = (v:number) => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v)

type Customer = { id:string; full_name:string; phone:string; email:string; address:string; city:string; province:string; postal_code:string; created_at:string }
type Order = { id:string; customer_id:string; total_amount:number; status:string; created_at:string; order_number:string }

export default function AdminCustomers(){
 const supabase=useMemo(()=>createClient(),[])
 const [customers,setCustomers]=useState<Customer[]>([]), [orders,setOrders]=useState<Order[]>([]), [q,setQ]=useState(''), [selected,setSelected]=useState<Customer|null>(null), [loading,setLoading]=useState(true), [error,setError]=useState('')
 useEffect(()=>{let alive=true;(async()=>{setLoading(true);setError('');const u=await supabase.auth.getUser();if(!u.data.user){if(alive){setError('Silakan login sebagai admin.');setLoading(false)};return}const [c,o]=await Promise.all([supabase.from('btp_customers').select('id,full_name,phone,email,address,city,province,postal_code,created_at').order('created_at',{ascending:false}),supabase.from('btp_orders').select('id,customer_id,total_amount,status,created_at,order_number').order('created_at',{ascending:false})]);if(c.error||o.error){if(alive){setError(c.error?.message||o.error?.message||'Gagal memuat data.');setLoading(false)};return}if(alive){setCustomers((c.data||[]) as Customer[]);setOrders((o.data||[]) as Order[]);setLoading(false)}})();return()=>{alive=false}},[supabase])
 const filtered=customers.filter(c=>[c.full_name,c.phone,c.email,c.city,c.province].join(' ').toLowerCase().includes(q.toLowerCase()))
 const stats=(id:string)=>{const os=orders.filter(o=>o.customer_id===id);return {count:os.length,total:os.reduce((s,o)=>s+Number(o.total_amount||0),0)}}
 const selectedOrders=selected?orders.filter(o=>o.customer_id===selected.id):[]
 return <main className="container" style={{padding:'36px 0 60px'}}><AdminNav current="pelanggan" />
  <div style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'flex-end',flexWrap:'wrap'}}><div><p className="muted">B-TECH PHONE · ADMIN</p><h1 style={{marginBottom:6}}>Pelanggan</h1><p className="muted">Kelola profil pelanggan, alamat, riwayat order, dan nilai belanja.</p></div><Link className="btn ghost" href="/admin">← Dashboard</Link></div>
  {error&&<div style={{marginTop:20,padding:14,borderRadius:12,border:'1px solid #f1b8b8'}}>{error}</div>}
  {loading?<p className="muted" style={{marginTop:28}}>Memuat data pelanggan…</p>:<>
   <div style={{display:'flex',gap:12,marginTop:24,flexWrap:'wrap'}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari nama, WhatsApp, email, kota…" style={{flex:1,minWidth:260,padding:'12px 14px',borderRadius:12,border:'1px solid var(--border,#ddd)'}}/><div style={{padding:'12px 16px',borderRadius:12,border:'1px solid var(--border,#ddd)'}}>{filtered.length} pelanggan</div></div>
   <section style={{marginTop:16,border:'1px solid var(--border,#e5e7eb)',borderRadius:16,overflow:'hidden'}}><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={{textAlign:'left',padding:12}}>Pelanggan</th><th style={{textAlign:'left',padding:12}}>Kontak</th><th style={{textAlign:'left',padding:12}}>Lokasi</th><th style={{textAlign:'right',padding:12}}>Order</th><th style={{textAlign:'right',padding:12}}>Total Belanja</th><th style={{padding:12}}></th></tr></thead><tbody>{filtered.map(c=>{const s=stats(c.id);return <tr key={c.id} style={{borderTop:'1px solid var(--border,#e5e7eb)'}}><td style={{padding:12}}><b>{c.full_name||'Tanpa nama'}</b><div className="muted" style={{fontSize:12}}>{c.email||'—'}</div></td><td style={{padding:12}}>{c.phone||'—'}</td><td style={{padding:12}}>{[c.city,c.province].filter(Boolean).join(', ')||'—'}</td><td style={{padding:12,textAlign:'right'}}>{s.count}</td><td style={{padding:12,textAlign:'right'}}>{money(s.total)}</td><td style={{padding:12,textAlign:'right'}}><button className="btn ghost" onClick={()=>setSelected(c)}>Detail</button></td></tr>})}{filtered.length===0&&<tr><td colSpan={6} className="muted" style={{padding:24,textAlign:'center'}}>Pelanggan tidak ditemukan.</td></tr>}</tbody></table></div></section>
  </>}
  {selected&&<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.45)',zIndex:50,padding:20,overflow:'auto'}} onClick={()=>setSelected(null)}><div onClick={e=>e.stopPropagation()} style={{maxWidth:760,margin:'40px auto',background:'var(--card,#fff)',borderRadius:18,padding:24}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><p className="muted" style={{margin:0}}>DETAIL PELANGGAN</p><h2 style={{margin:'4px 0'}}>{selected.full_name||'Tanpa nama'}</h2></div><button className="btn ghost" onClick={()=>setSelected(null)}>Tutup</button></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12,marginTop:18}}>{[['WhatsApp',selected.phone],['Email',selected.email],['Alamat',selected.address],['Kota',selected.city],['Provinsi',selected.province],['Kode Pos',selected.postal_code]].map(([a,b])=><div key={a} style={{padding:14,border:'1px solid var(--border,#e5e7eb)',borderRadius:12}}><small className="muted">{a}</small><div style={{marginTop:5}}>{b||'—'}</div></div>)}</div><h3 style={{marginTop:24}}>Riwayat pesanan</h3>{selectedOrders.length===0?<p className="muted">Belum ada pesanan.</p>:<div style={{display:'grid',gap:8}}>{selectedOrders.slice(0,10).map(o=><div key={o.id} style={{display:'flex',justifyContent:'space-between',gap:12,padding:12,border:'1px solid var(--border,#e5e7eb)',borderRadius:10}}><div><b>{o.order_number}</b><div className="muted" style={{fontSize:12}}>{new Date(o.created_at).toLocaleString('id-ID')} · {o.status}</div></div><b>{money(Number(o.total_amount||0))}</b></div>)}</div>}</div></div>}
 </main>
}
