'use client'
import { useEffect, useMemo, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import AdminNav from '../AdminNav'

type Product={id:string;brand_id:string;name:string;slug:string;category:string;description:string|null;short_description:string|null;image_url:string|null;is_active:boolean;is_featured:boolean;brand?:{name:string}|{name:string}[]|null}
type Variant={id:string;product_id:string;sku:string;variant_name:string;color:string|null;storage:string|null;ram:string|null;price:number;compare_at_price:number|null;imei_required:boolean;is_active:boolean;inventory?:{id:string;stock_quantity:number;reserved_quantity:number;low_stock_threshold:number}|{id:string;stock_quantity:number;reserved_quantity:number;low_stock_threshold:number}[]|null}
type Brand={id:string;name:string;slug:string;logo_url:string|null;is_active:boolean}
const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n)
const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9\s-]/g,'').replace(/\s+/g,'-').replace(/-+/g,'-')
const emptyProduct={brand_id:'',name:'',slug:'',category:'smartphone',description:'',short_description:'',image_url:'',is_active:true,is_featured:false}
const emptyVariant={sku:'',variant_name:'',color:'',storage:'',ram:'',price:'',compare_at_price:'',imei_required:false,is_active:true}
export default function AdminProducts(){
 const s=useMemo(()=>createClient(),[])
 const [products,setProducts]=useState<Product[]>([]);const [variants,setVariants]=useState<Variant[]>([]);const [brands,setBrands]=useState<Brand[]>([]);const [stockForm,setStockForm]=useState<any>(null);const [brandForm,setBrandForm]=useState<any>(null)
 const [q,setQ]=useState('');const [brand,setBrand]=useState('all');const [status,setStatus]=useState('all');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [msg,setMsg]=useState('')
 const [selected,setSelected]=useState<string|null>(null);const [productForm,setProductForm]=useState<any>(null);const [variantForm,setVariantForm]=useState<any>(null)
 async function load(){setLoading(true);const [p,v,b]=await Promise.all([s.from('btp_products').select('id,brand_id,name,slug,category,description,short_description,image_url,is_active,is_featured,brand:btp_brands(name)').order('name'),s.from('btp_product_variants').select('id,product_id,sku,variant_name,color,storage,ram,price,compare_at_price,imei_required,is_active,inventory:btp_inventory(id,stock_quantity,reserved_quantity,low_stock_threshold)').order('variant_name'),s.from('btp_brands').select('id,name,slug,logo_url,is_active').order('name')]);if(p.error||v.error||b.error)setMsg(p.error?.message||v.error?.message||b.error?.message||'Gagal memuat katalog.');else{setProducts((p.data||[]) as Product[]);setVariants((v.data||[]) as Variant[]);setBrands((b.data||[]) as Brand[])}setLoading(false)}
 useEffect(()=>{load()},[])
 const brandName=(p:Product)=>Array.isArray(p.brand)?p.brand[0]?.name:p.brand?.name
 const brandOptions=[...new Set(products.map(brandName).filter(Boolean) as string[])]
 const shown=products.filter(p=>{const bn=brandName(p);const x=[p.name,p.slug,p.category,bn,...variants.filter(v=>v.product_id===p.id).map(v=>v.sku)].join(' ').toLowerCase();return(!q||x.includes(q.toLowerCase()))&&(brand==='all'||bn===brand)&&(status==='all'||(status==='active'?p.is_active:!p.is_active))})
 const pv=(id:string)=>variants.filter(v=>v.product_id===id)
 const inventorySummary=(id:string)=>{const list=pv(id);let available=0,low=0,out=0;list.forEach(v=>{const i=Array.isArray(v.inventory)?v.inventory[0]:v.inventory;const av=Math.max(0,(i?.stock_quantity??0)-(i?.reserved_quantity??0));available+=av;if(av===0)out++;else if(av<=(i?.low_stock_threshold??2))low++});return {available,low,out}}
 function notify(text:string){setMsg(text);window.setTimeout(()=>setMsg(''),3500)}
 async function saveBrand(e:React.FormEvent){e.preventDefault();if(!brandForm.name){notify('Nama brand wajib diisi.');return}setBusy('brand');const slug=slugify(brandForm.slug||brandForm.name);const payload={name:brandForm.name.trim(),slug,logo_url:brandForm.logo_url?.trim()||null,is_active:!!brandForm.is_active,updated_at:new Date().toISOString()};const query=brandForm.id?s.from('btp_brands').update(payload).eq('id',brandForm.id):s.from('btp_brands').insert(payload);const {error}=await query;if(error)notify(error.code==='23505'?'Nama atau slug brand sudah digunakan.':error.message);else{notify(brandForm.id?'Brand diperbarui.':'Brand berhasil ditambahkan.');setBrandForm(null);await load()}setBusy('')}
 async function toggleBrand(b:Brand){setBusy(b.id);const {error}=await s.from('btp_brands').update({is_active:!b.is_active,updated_at:new Date().toISOString()}).eq('id',b.id);if(error)notify(error.message);else await load();setBusy('')}
 async function saveProduct(e:React.FormEvent){e.preventDefault();if(!productForm.name||!productForm.brand_id){notify('Nama produk dan brand wajib diisi.');return}if(productForm.slug && !slugify(productForm.slug)){notify('Slug produk tidak valid.');return}setBusy('product');const payload={...productForm,slug:slugify(productForm.slug||productForm.name),description:productForm.description||null,short_description:productForm.short_description||null,image_url:productForm.image_url||null,updated_at:new Date().toISOString()};const query=productForm.id?s.from('btp_products').update(payload).eq('id',productForm.id):s.from('btp_products').insert(payload);const {error}=await query;if(error)notify(error.message);else{notify(productForm.id?'Produk diperbarui.':'Produk berhasil ditambahkan.');setProductForm(null);await load()}setBusy('')}
 async function saveVariant(e:React.FormEvent){e.preventDefault();if(!variantForm.product_id||!variantForm.sku||!variantForm.variant_name||variantForm.price===''){notify('SKU, nama varian, dan harga wajib diisi.');return}const price=Number(variantForm.price);const compare=variantForm.compare_at_price===''||variantForm.compare_at_price==null?null:Number(variantForm.compare_at_price);if(!Number.isFinite(price)||price<0){notify('Harga harus berupa angka 0 atau lebih.');return}if(compare!==null&&(!Number.isFinite(compare)||compare<0)){notify('Harga pembanding harus berupa angka 0 atau lebih.');return}setBusy('variant');const payload={...variantForm,sku:String(variantForm.sku).trim(),variant_name:String(variantForm.variant_name).trim(),price,compare_at_price:compare,color:variantForm.color||null,storage:variantForm.storage||null,ram:variantForm.ram||null,updated_at:new Date().toISOString()};const query=variantForm.id?s.from('btp_product_variants').update(payload).eq('id',variantForm.id):s.from('btp_product_variants').insert(payload);const {error}=await query;if(error)notify(error.code==='23505'?'SKU sudah digunakan oleh varian lain.':error.message);else{notify(variantForm.id?'Varian diperbarui.':'Varian berhasil ditambahkan.');setVariantForm(null);await load()}setBusy('')}
 async function toggleProduct(p:Product,field:'is_active'|'is_featured'){setBusy(p.id);const {error}=await s.from('btp_products').update({[field]:!p[field],updated_at:new Date().toISOString()}).eq('id',p.id);if(error)notify(error.message);else await load();setBusy('')}
 async function toggleVariant(v:Variant){setBusy(v.id);const {error}=await s.from('btp_product_variants').update({is_active:!v.is_active,updated_at:new Date().toISOString()}).eq('id',v.id);if(error)notify(error.message);else await load();setBusy('')}
 async function saveStock(e:React.FormEvent){e.preventDefault();if(!stockForm)return;setBusy('stock');const existing=Array.isArray(stockForm.inventory)?stockForm.inventory[0]:stockForm.inventory;const payload={stock_quantity:Math.max(0,Number(stockForm.stock_quantity||0)),low_stock_threshold:Math.max(0,Number(stockForm.low_stock_threshold||0)),updated_at:new Date().toISOString()};const query=existing?.id?s.from('btp_inventory').update(payload).eq('id',existing.id):s.from('btp_inventory').insert({...payload,variant_id:stockForm.id,reserved_quantity:0});const {error}=await query;if(error)notify(error.message);else{notify('Stok diperbarui.');setStockForm(null);await load()}setBusy('')}
 async function deleteVariant(v:Variant){if(!window.confirm('Hapus varian ini? Data akan dihapus permanen. Pastikan varian belum dipakai transaksi.'))return;setBusy(v.id);const {error}=await s.from('btp_product_variants').delete().eq('id',v.id);if(error)notify('Varian tidak dapat dihapus. Jika sudah terkait inventory/transaksi, gunakan Nonaktifkan.');else{notify('Varian dihapus.');await load()}setBusy('')}
 async function deleteProduct(p:Product){if(pv(p.id).length){notify('Produk masih memiliki varian. Hapus/nonaktifkan variannya terlebih dahulu.');return}if(!window.confirm('Hapus produk ini secara permanen?'))return;setBusy(p.id);const {error}=await s.from('btp_products').delete().eq('id',p.id);if(error)notify('Produk tidak dapat dihapus. Gunakan Nonaktifkan jika sudah digunakan.');else{notify('Produk dihapus.');await load()}setBusy('')}
 const input=(label:string,key:string,form:any,setForm:any,extra:any={})=><label style={{display:'grid',gap:6}}><span style={{fontWeight:650}}>{label}</span><input {...extra} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})} style={{padding:'11px 12px',borderRadius:10,border:'1px solid var(--border,#ddd)',width:'100%',boxSizing:'border-box'}}/></label>
 return <main className="container" style={{padding:'36px 0 60px'}}><AdminNav current="produk"/><div style={{display:'flex',justifyContent:'space-between',gap:18,alignItems:'flex-end',flexWrap:'wrap'}}><div><p className="muted">B-TECH PHONE · CATALOG</p><h1 style={{marginBottom:6}}>Produk & Varian</h1><p className="muted">CRUD katalog, harga, status tayang, unggulan, dan SKU.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn ghost" onClick={()=>setBrandForm({name:'',slug:'',logo_url:'',is_active:true})}>+ Brand</button><button className="btn primary" onClick={()=>setProductForm({...emptyProduct})}>+ Tambah Produk</button></div></div>{msg&&<div style={{marginTop:18,padding:12,borderRadius:12,border:'1px solid var(--border,#e5e7eb)'}}>{msg}</div>}
 <section className="card" style={{marginTop:18,padding:14}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,flexWrap:'wrap'}}><strong>Brand</strong><span className="muted">{brands.filter(b=>b.is_active).length} aktif · {brands.filter(b=>!b.is_active).length} nonaktif</span></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}>{brands.map(b=><button key={b.id} className="btn ghost" onClick={()=>setBrandForm({...b})}>{b.name}{!b.is_active?' · nonaktif':''}</button>)}</div></section><div style={{display:'flex',gap:10,marginTop:22,flexWrap:'wrap'}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari nama, brand, kategori, SKU…" style={{flex:1,minWidth:260,padding:'12px 14px',borderRadius:12,border:'1px solid var(--border,#ddd)'}}/><select value={status} onChange={e=>setStatus(e.target.value)} style={{padding:'12px 14px',borderRadius:12,border:'1px solid var(--border,#ddd)'}}><option value="all">Semua status</option><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select><select value={brand} onChange={e=>setBrand(e.target.value)} style={{padding:'12px 14px',borderRadius:12,border:'1px solid var(--border,#ddd)'}}><option value="all">Semua brand</option>{brandOptions.map(b=><option key={b} value={b}>{b}</option>)}</select><div style={{padding:'12px 15px',borderRadius:12,border:'1px solid var(--border,#ddd)'}}>{shown.length} produk</div></div>
 {loading?<p className="muted" style={{marginTop:28}}>Memuat katalog…</p>:<section style={{display:'grid',gap:12,marginTop:16}}>{shown.map(p=><article key={p.id} className="card" style={{padding:18}}><div style={{display:'flex',justifyContent:'space-between',gap:14,alignItems:'flex-start',flexWrap:'wrap'}}><div style={{display:'flex',gap:14}}>{p.image_url?<img src={p.image_url} alt={p.name} style={{width:64,height:64,objectFit:'contain',borderRadius:12,border:'1px solid var(--border,#e5e7eb)'}}/>:<div style={{width:64,height:64,borderRadius:12,border:'1px solid var(--border,#e5e7eb)',display:'grid',placeItems:'center'}} className="muted">IMG</div>}<div><h3 style={{margin:'0 0 4px'}}>{p.name}</h3><div className="muted">{brandName(p)||'—'} · {p.category}</div><div style={{display:'flex',gap:6,marginTop:8,flexWrap:'wrap'}}><span className="badge">{p.is_active?'AKTIF':'NONAKTIF'}</span>{p.is_featured&&<span className="badge">UNGGULAN</span>}<span className="muted">{pv(p.id).length} varian</span>{(()=>{const x=inventorySummary(p.id);return <><span className="badge">Stok {x.available}</span>{x.out>0&&<span className="badge">⛔ {x.out} habis</span>}{x.low>0&&<span className="badge">⚠ {x.low} stok rendah</span>}</>})()}</div></div></div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}><button className="btn ghost" onClick={()=>setProductForm({...p,description:p.description||'',short_description:p.short_description||'',image_url:p.image_url||''})}>Edit</button><button className="btn ghost" disabled={busy===p.id} onClick={()=>toggleProduct(p,'is_active')}>{p.is_active?'Nonaktifkan':'Aktifkan'}</button><button className="btn ghost" disabled={busy===p.id} onClick={()=>toggleProduct(p,'is_featured')}>{p.is_featured?'Hapus Unggulan':'Jadikan Unggulan'}</button><button className="btn primary" onClick={()=>setSelected(selected===p.id?null:p.id)}>{selected===p.id?'Tutup':'Varian'}</button><button className="btn ghost" disabled={busy===p.id} onClick={()=>deleteProduct(p)}>Hapus</button></div></div>
 {selected===p.id&&<div style={{marginTop:16,paddingTop:16,borderTop:'1px solid var(--border,#e5e7eb)'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,flexWrap:'wrap'}}><h4 style={{margin:0}}>Varian produk</h4><button className="btn primary" onClick={()=>setVariantForm({...emptyVariant,product_id:p.id})}>+ Tambah Varian</button></div><div style={{overflowX:'auto',marginTop:10}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={{textAlign:'left',padding:9}}>SKU</th><th style={{textAlign:'left',padding:9}}>Varian</th><th style={{textAlign:'right',padding:9}}>Harga</th><th style={{textAlign:'center',padding:9}}>Stok</th><th style={{textAlign:'center',padding:9}}>Status</th><th style={{padding:9}}></th></tr></thead><tbody>{pv(p.id).map(v=><tr key={v.id} style={{borderTop:'1px solid var(--border,#e5e7eb)'}}><td style={{padding:9}}>{v.sku}</td><td style={{padding:9}}>{v.variant_name}{v.color?' · '+v.color:''}{v.storage?' · '+v.storage:''}{v.ram?' · '+v.ram:''}</td><td style={{padding:9,textAlign:'right'}}>{money(Number(v.price||0))}</td><td style={{padding:9,textAlign:'center'}}>{(()=>{const i=Array.isArray(v.inventory)?v.inventory[0]:v.inventory;const av=Math.max(0,(i?.stock_quantity??0)-(i?.reserved_quantity??0));return <span className="badge">Stok {i?.stock_quantity??0} · Tersedia {av}{av===0?' · ⛔ Habis':av<=(i?.low_stock_threshold??2)?' · ⚠ Rendah':''}</span>})()}</td><td style={{padding:9,textAlign:'center'}}><span className="badge">{v.is_active?'AKTIF':'NONAKTIF'}</span></td><td style={{padding:9,textAlign:'right'}}><button className="btn ghost" onClick={()=>setVariantForm({...v,price:String(v.price??''),compare_at_price:v.compare_at_price==null?'':String(v.compare_at_price)})}>Edit</button> <button className="btn ghost" onClick={()=>{const i=Array.isArray(v.inventory)?v.inventory[0]:v.inventory;setStockForm({...v,stock_quantity:i?.stock_quantity??0,low_stock_threshold:i?.low_stock_threshold??2})}}>Stok</button> <button className="btn ghost" disabled={busy===v.id} onClick={()=>toggleVariant(v)}>{v.is_active?'Nonaktifkan':'Aktifkan'}</button> <button className="btn ghost" disabled={busy===v.id} onClick={()=>deleteVariant(v)}>Hapus</button></td></tr>)}</tbody></table></div>{!pv(p.id).length&&<p className="muted">Belum ada varian.</p>}</div>}</article>)}{!shown.length&&<div className="card" style={{padding:30,textAlign:'center'}}><p className="muted">Produk tidak ditemukan.</p></div>}</section>}
 {brandForm&&<div style={modal}><form onSubmit={saveBrand} className="card" style={{...formCard,maxWidth:560}}><h2>{brandForm.id?'Edit Brand':'Tambah Brand'}</h2><div style={grid}>{input('Nama brand','name',brandForm,setBrandForm)}{input('Slug','slug',brandForm,setBrandForm,{placeholder:'otomatis dari nama'})}{input('Logo URL','logo_url',brandForm,setBrandForm,{placeholder:'https://…'})}</div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,marginTop:12,flexWrap:'wrap'}}><p className="muted" style={{margin:0}}>Brand nonaktif tidak muncul pada pilihan produk baru.</p>{brandForm.id&&<button type="button" className="btn ghost" onClick={()=>toggleBrand(brandForm)} disabled={busy===brandForm.id}>{brandForm.is_active?'Nonaktifkan':'Aktifkan'}</button>}</div><div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:18}}><button type="button" className="btn ghost" onClick={()=>setBrandForm(null)}>Batal</button><button className="btn primary" disabled={busy==='brand'}>{busy==='brand'?'Menyimpan…':'Simpan Brand'}</button></div></form></div>}{productForm&&<div style={modal}><form onSubmit={saveProduct} className="card" style={formCard}><h2>{productForm.id?'Edit Produk':'Tambah Produk'}</h2><div style={grid}>{input('Nama produk','name',productForm,setProductForm)}{input('Slug','slug',productForm,setProductForm,{placeholder:'otomatis dari nama'})}<label style={{display:'grid',gap:6}}><span style={{fontWeight:650}}>Brand</span><select required value={productForm.brand_id} onChange={e=>setProductForm({...productForm,brand_id:e.target.value})} style={selectStyle}><option value="">Pilih brand</option>{brands.filter(b=>b.is_active).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label style={{display:'grid',gap:6}}><span style={{fontWeight:650}}>Kategori</span><select value={productForm.category} onChange={e=>setProductForm({...productForm,category:e.target.value})} style={selectStyle}><option value="smartphone">Smartphone</option><option value="tablet">Tablet</option><option value="ipad">iPad</option><option value="apple_other">Apple Other</option></select></label>{input('Short description','short_description',productForm,setProductForm)}{input('Image URL','image_url',productForm,setProductForm,{placeholder:'https://…'})}<label style={{display:'grid',gap:6,gridColumn:'1/-1'}}><span style={{fontWeight:650}}>Description</span><textarea value={productForm.description??''} onChange={e=>setProductForm({...productForm,description:e.target.value})} rows={5} style={{padding:11,borderRadius:10,border:'1px solid var(--border,#ddd)'}}/></label></div><div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:18}}><button type="button" className="btn ghost" onClick={()=>setProductForm(null)}>Batal</button><button className="btn primary" disabled={busy==='product'}>{busy==='product'?'Menyimpan…':'Simpan Produk'}</button></div></form></div>}
 {stockForm&&<div style={modal}><form onSubmit={saveStock} className="card" style={{...formCard,maxWidth:520}}><h2>Stok · {stockForm.sku}</h2><div style={grid}>{input('Stok fisik','stock_quantity',stockForm,setStockForm,{type:'number',min:0,step:'1'})}{input('Batas stok rendah','low_stock_threshold',stockForm,setStockForm,{type:'number',min:0,step:'1'})}</div><p className="muted" style={{marginTop:12}}>Stok reserved dikelola otomatis oleh alur pesanan dan tidak dapat diubah dari form ini.</p><div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:18}}><button type="button" className="btn ghost" onClick={()=>setStockForm(null)}>Batal</button><button className="btn primary" disabled={busy==='stock'}>{busy==='stock'?'Menyimpan…':'Simpan Stok'}</button></div></form></div>}
 {variantForm&&<div style={modal}><form onSubmit={saveVariant} className="card" style={formCard}><h2>{variantForm.id?'Edit Varian':'Tambah Varian'}</h2><div style={grid}>{input('SKU','sku',variantForm,setVariantForm)}{input('Nama varian','variant_name',variantForm,setVariantForm)}{input('Warna','color',variantForm,setVariantForm)}{input('Storage','storage',variantForm,setVariantForm)}{input('RAM','ram',variantForm,setVariantForm)}{input('Harga','price',variantForm,setVariantForm,{type:'number',min:0,step:'1'})}{input('Harga pembanding','compare_at_price',variantForm,setVariantForm,{type:'number',min:0,step:'1'})}<label style={{display:'flex',alignItems:'center',gap:8}}><input type="checkbox" checked={!!variantForm.imei_required} onChange={e=>setVariantForm({...variantForm,imei_required:e.target.checked})}/><span>IMEI wajib</span></label></div><div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:18}}><button type="button" className="btn ghost" onClick={()=>setVariantForm(null)}>Batal</button><button className="btn primary" disabled={busy==='variant'}>{busy==='variant'?'Menyimpan…':'Simpan Varian'}</button></div></form></div>}
 </main>
}
const modal:React.CSSProperties={position:'fixed',inset:0,zIndex:50,background:'rgba(0,0,0,.45)',display:'grid',placeItems:'center',padding:16,overflowY:'auto'}
const formCard:React.CSSProperties={width:'min(760px,100%)',padding:22,maxHeight:'90vh',overflowY:'auto'}
const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:14}
const selectStyle:React.CSSProperties={padding:'11px 12px',borderRadius:10,border:'1px solid var(--border,#ddd)',width:'100%',boxSizing:'border-box'}
